"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { ArrowLeft, Building2, CalendarCheck2, Stethoscope } from "lucide-react";
import { useToast } from "@/components/ToastProvider";

type Item = Record<string, unknown>;
export default function CareNetworkAdminPage() {
  const { showToast } = useToast(); const [data, setData] = useState<{ networks: Item[]; institutions: Item[]; departments: Item[]; practitioners: Item[]; referralRoutes: Item[] }>({ networks: [], institutions: [], departments: [], practitioners: [], referralRoutes: [] });
  const [institution, setInstitution] = useState({ name: "", type: "tertiary", level: "", officialUrl: "", registrationUrl: "", sourceUrl: "" });
  const [doctor, setDoctor] = useState({ institutionId: "", name: "", title: "", specialties: "", sourceUrl: "" });
  const [schedule, setSchedule] = useState({ institutionId: "", practitionerId: "", startsAt: "", endsAt: "", location: "", sourceUrl: "", note: "" });
  const [route, setRoute] = useState({ fromId: "", toId: "", name: "", tags: "", officialUrl: "" });
  const load = useCallback(async () => { const response = await fetch("/api/v1/admin/care-network", { cache: "no-store" }); const payload = await response.json(); if (response.ok) setData(payload.data); }, []);
  useEffect(() => { void load(); }, [load]);
  async function save(body: unknown) { const response = await fetch("/api/v1/admin/care-network", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const payload = await response.json(); if (!response.ok) return showToast(payload.error?.message ?? "保存失败", "warning"); showToast("医疗网络配置已保存。", "success"); await load(); }
  async function importSchedule(event: FormEvent) { event.preventDefault(); const response = await fetch("/api/v1/admin/schedules/import", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ schedules: [{ institutionId: schedule.institutionId, practitionerId: schedule.practitionerId || null, startsAt: new Date(schedule.startsAt).toISOString(), endsAt: new Date(schedule.endsAt).toISOString(), serviceMode: "clinic", location: schedule.location || null, sourceUrl: schedule.sourceUrl || null, note: schedule.note || null }] }) }); const payload = await response.json(); if (!response.ok) return showToast(payload.error?.message ?? "排班导入失败", "warning"); showToast("排班已进入待核验队列。", "success"); setSchedule((value) => ({ ...value, startsAt: "", endsAt: "", location: "", sourceUrl: "", note: "" })); }
  const input = "h-11 w-full rounded-md border border-line px-3 text-sm outline-none focus:border-sage";
  return <main className="min-h-dvh bg-[#F3F5F4] text-navy"><header className="border-b border-line bg-white"><div className="mx-auto flex max-w-7xl items-center gap-3 px-5 py-4"><Link href="/admin" className="flex h-10 w-10 items-center justify-center rounded-md border border-line"><ArrowLeft className="h-4 w-4" /></Link><div><h1 className="text-xl font-semibold">分级诊疗网络配置</h1><p className="mt-1 text-xs text-navy/50">只录入已确认的机构、医生、排班和转诊路线</p></div></div></header><div className="mx-auto max-w-7xl px-5 py-6">
    <section className="grid gap-4 lg:grid-cols-2"><form onSubmit={(event) => { event.preventDefault(); void save({ entity: "institution", name: institution.name, institutionType: institution.type, levelLabel: institution.level || null, officialUrl: institution.officialUrl || null, registrationUrl: institution.registrationUrl || null, sourceUrl: institution.sourceUrl || null, networkRole: institution.type === "community" ? "primary_care" : "referral" }); }} className="rounded-md border border-line bg-white p-5"><h2 className="flex items-center gap-2 font-semibold"><Building2 className="h-4 w-4 text-sage" />添加正式机构</h2><div className="mt-4 grid gap-3"><input required value={institution.name} onChange={(e) => setInstitution({ ...institution, name: e.target.value })} placeholder="机构全称" className={input} /><div className="grid grid-cols-2 gap-2"><select value={institution.type} onChange={(e) => setInstitution({ ...institution, type: e.target.value })} className={input}><option value="community">社区中心</option><option value="secondary">二级医院</option><option value="tertiary">三级医院</option><option value="public_service">公共服务机构</option></select><input value={institution.level} onChange={(e) => setInstitution({ ...institution, level: e.target.value })} placeholder="等级说明" className={input} /></div><input value={institution.officialUrl} onChange={(e) => setInstitution({ ...institution, officialUrl: e.target.value })} placeholder="官方网站 HTTPS" className={input} /><input value={institution.registrationUrl} onChange={(e) => setInstitution({ ...institution, registrationUrl: e.target.value })} placeholder="官方挂号入口 HTTPS" className={input} /><input value={institution.sourceUrl} onChange={(e) => setInstitution({ ...institution, sourceUrl: e.target.value })} placeholder="合作关系或资料来源 URL" className={input} /><button className="rounded-md bg-navy px-4 py-3 text-sm font-semibold text-white">保存机构</button></div></form>
      <form onSubmit={(event) => { event.preventDefault(); void save({ entity: "practitioner", institutionId: doctor.institutionId, name: doctor.name, title: doctor.title || null, specialties: doctor.specialties.split(/[、,，]/).map((v) => v.trim()).filter(Boolean), sourceUrl: doctor.sourceUrl || null }); }} className="rounded-md border border-line bg-white p-5"><h2 className="flex items-center gap-2 font-semibold"><Stethoscope className="h-4 w-4 text-sage" />添加医生</h2><div className="mt-4 grid gap-3"><select required value={doctor.institutionId} onChange={(e) => setDoctor({ ...doctor, institutionId: e.target.value })} className={input}><option value="">选择所属机构</option>{data.institutions.map((item) => <option key={String(item.id)} value={String(item.id)}>{String(item.name)}</option>)}</select><input required value={doctor.name} onChange={(e) => setDoctor({ ...doctor, name: e.target.value })} placeholder="医生姓名" className={input} /><input value={doctor.title} onChange={(e) => setDoctor({ ...doctor, title: e.target.value })} placeholder="职称" className={input} /><input value={doctor.specialties} onChange={(e) => setDoctor({ ...doctor, specialties: e.target.value })} placeholder="擅长，使用顿号分隔" className={input} /><input value={doctor.sourceUrl} onChange={(e) => setDoctor({ ...doctor, sourceUrl: e.target.value })} placeholder="医生信息来源 URL" className={input} /><button className="rounded-md bg-navy px-4 py-3 text-sm font-semibold text-white">保存医生</button></div></form>
      <form onSubmit={importSchedule} className="rounded-md border border-line bg-white p-5"><h2 className="flex items-center gap-2 font-semibold"><CalendarCheck2 className="h-4 w-4 text-sage" />导入单条排班</h2><div className="mt-4 grid gap-3"><select required value={schedule.institutionId} onChange={(e) => setSchedule({ ...schedule, institutionId: e.target.value, practitionerId: "" })} className={input}><option value="">选择机构</option>{data.institutions.map((item) => <option key={String(item.id)} value={String(item.id)}>{String(item.name)}</option>)}</select><select value={schedule.practitionerId} onChange={(e) => setSchedule({ ...schedule, practitionerId: e.target.value })} className={input}><option value="">未指定医生</option>{data.practitioners.filter((item) => item.institution_id === schedule.institutionId).map((item) => <option key={String(item.id)} value={String(item.id)}>{String(item.name)}</option>)}</select><div className="grid grid-cols-2 gap-2"><input required type="datetime-local" value={schedule.startsAt} onChange={(e) => setSchedule({ ...schedule, startsAt: e.target.value })} className={input} /><input required type="datetime-local" value={schedule.endsAt} onChange={(e) => setSchedule({ ...schedule, endsAt: e.target.value })} className={input} /></div><input value={schedule.location} onChange={(e) => setSchedule({ ...schedule, location: e.target.value })} placeholder="坐班地点" className={input} /><input type="url" value={schedule.sourceUrl} onChange={(e) => setSchedule({ ...schedule, sourceUrl: e.target.value })} placeholder="官方排班来源 URL（推荐）" className={input} /><input value={schedule.note} onChange={(e) => setSchedule({ ...schedule, note: e.target.value })} placeholder="核验依据或联系人说明" className={input} /><button className="rounded-md bg-navy px-4 py-3 text-sm font-semibold text-white">导入待核验排班</button></div></form>
      <form onSubmit={(event) => { event.preventDefault(); void save({ entity: "referralRoute", careNetworkId: String(data.networks[0]?.id ?? ""), fromInstitutionId: route.fromId, toInstitutionId: route.toId, name: route.name, problemTags: route.tags.split(/[、,，]/).map((v) => v.trim()).filter(Boolean), officialUrl: route.officialUrl || null }); }} className="rounded-md border border-line bg-white p-5"><h2 className="font-semibold">配置转诊路线</h2><div className="mt-4 grid gap-3"><div className="grid grid-cols-2 gap-2"><select required value={route.fromId} onChange={(e) => setRoute({ ...route, fromId: e.target.value })} className={input}><option value="">从社区/机构</option>{data.institutions.map((item) => <option key={String(item.id)} value={String(item.id)}>{String(item.name)}</option>)}</select><select required value={route.toId} onChange={(e) => setRoute({ ...route, toId: e.target.value })} className={input}><option value="">上转到机构</option>{data.institutions.map((item) => <option key={String(item.id)} value={String(item.id)}>{String(item.name)}</option>)}</select></div><input required value={route.name} onChange={(e) => setRoute({ ...route, name: e.target.value })} placeholder="路线名称" className={input} /><input value={route.tags} onChange={(e) => setRoute({ ...route, tags: e.target.value })} placeholder="适用问题标签" className={input} /><input value={route.officialUrl} onChange={(e) => setRoute({ ...route, officialUrl: e.target.value })} placeholder="官方办理说明 URL" className={input} /><button className="rounded-md bg-navy px-4 py-3 text-sm font-semibold text-white">保存转诊路线</button></div></form></section>
    <section className="mt-6 rounded-md border border-line bg-white p-5"><h2 className="font-semibold">当前网络</h2><div className="mt-4 divide-y divide-line">{data.institutions.map((item) => <div key={String(item.id)} className="flex items-center justify-between gap-3 py-3"><div><p className="text-sm font-semibold">{String(item.name)}</p><p className="mt-1 text-xs text-navy/45">{String(item.institution_type)} · 医生 {data.practitioners.filter((doctorItem) => doctorItem.institution_id === item.id).length} 人</p></div></div>)}</div></section>
  </div></main>;
}
