"use client";

import { useCallback, useEffect, useState } from "react";
import Link from "next/link";
import { Activity, ArrowLeft, BookOpen, CalendarCheck2, CheckCircle2, MessageCircleMore, RefreshCw, UserRoundCheck, XCircle } from "lucide-react";
import { useToast } from "@/components/ToastProvider";

type Tab = "bindings" | "facts" | "content" | "schedules" | "broadcasts";
export default function OperationsPage() {
  const { showToast } = useToast(); const [tab, setTab] = useState<Tab>("bindings"); const [bindings, setBindings] = useState<Array<Record<string, unknown>>>([]); const [facts, setFacts] = useState<Array<Record<string, unknown>>>([]); const [content, setContent] = useState<Array<Record<string, unknown>>>([]); const [schedules, setSchedules] = useState<Array<Record<string, unknown>>>([]); const [broadcasts, setBroadcasts] = useState<Array<Record<string, unknown>>>([]); const [loading, setLoading] = useState(true);
  const load = useCallback(async () => {
    setLoading(true);
    const endpoints = ["/api/v1/staff/care-bindings?status=pending", "/api/v1/staff/group-work-queue", "/api/v1/admin/content-sources", "/api/v1/admin/schedules", "/api/v1/admin/broadcasts"];
    const responses = await Promise.all(endpoints.map((url) => fetch(url, { cache: "no-store" }).then(async (response) => ({ ok: response.ok, payload: await response.json() })).catch(() => ({ ok: false, payload: null }))));
    if (responses[0].ok) setBindings(responses[0].payload.data.bindings ?? []);
    if (responses[1].ok) setFacts(responses[1].payload.data.candidates ?? []);
    if (responses[2].ok) setContent(responses[2].payload.data.candidates ?? []);
    if (responses[3].ok) setSchedules(responses[3].payload.data.schedules ?? []);
    if (responses[4].ok) setBroadcasts(responses[4].payload.data.broadcasts ?? []);
    setLoading(false);
  }, []);
  useEffect(() => { void load(); }, [load]);
  async function fact(id: string, decision: "confirm" | "reject") { const response = await fetch(`/api/v1/staff/fact-candidates/${id}/${decision}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: "{}" }); const payload = await response.json(); if (!response.ok) return showToast(payload.error?.message ?? "操作失败", "warning"); showToast(decision === "confirm" ? "事实已确认并写入相应服务记录。" : "候选事实已拒绝。", "success"); await load(); }
  async function review(id: string, decision: "publish" | "reject") { const response = await fetch("/api/v1/admin/content-sources/review", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ itemId: id, decision, note: decision === "publish" ? "运营人员审核通过" : "内容不适合发布", expiresAt: decision === "publish" ? new Date(Date.now() + 90 * 86_400_000).toISOString() : null }) }); const payload = await response.json(); if (!response.ok) return showToast(payload.error?.message ?? "审核失败", "warning"); showToast("内容审核状态已更新。", "success"); await load(); }
  async function verify(id: string, decision: "verified" | "cancelled") { const response = await fetch("/api/v1/admin/schedules/verify", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ scheduleIds: [id], decision, note: decision === "verified" ? "机构负责人核验" : "排班取消" }) }); const payload = await response.json(); if (!response.ok) return showToast(payload.error?.message ?? "核验失败", "warning"); showToast("排班状态已更新。", "success"); await load(); }
  async function reviewBinding(id: string, decision: "active" | "pending" | "revoked") { const response = await fetch("/api/v1/staff/care-bindings", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ bindingId: id, decision, note: decision === "active" ? "已核对居民所属社区及家医签约关系" : "资料不一致，请居民联系社区补充核验" }) }); const payload = await response.json(); if (!response.ok) return showToast(payload.error?.message ?? "签约核验失败", "warning"); showToast(decision === "active" ? "签约关系已核验，居民服务权限已开放。" : "该登记已退回补充核验。", "success"); await load(); }
  const tabs: Array<{ id: Tab; label: string; icon: typeof Activity; count: number }> = [{ id: "bindings", label: "签约核验", icon: UserRoundCheck, count: bindings.length }, { id: "facts", label: "群事实", icon: MessageCircleMore, count: facts.length }, { id: "content", label: "内容审核", icon: BookOpen, count: content.length }, { id: "schedules", label: "排班核验", icon: CalendarCheck2, count: schedules.filter((item) => item.status === "draft").length }, { id: "broadcasts", label: "群通知", icon: Activity, count: broadcasts.length }];
  return <main className="min-h-dvh bg-[#F3F5F4] text-navy"><header className="border-b border-line bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><div className="flex items-center gap-3"><Link href="/doctor" aria-label="返回工作台" className="flex h-10 w-10 items-center justify-center rounded-md border border-line"><ArrowLeft className="h-4 w-4" /></Link><div><h1 className="text-xl font-semibold">家医运营工作台</h1><p className="mt-1 text-xs text-navy/50">群事实、内容、排班和通知均需人工确认</p></div></div><button onClick={() => void load()} aria-label="刷新" className="flex h-10 w-10 items-center justify-center rounded-md border border-line bg-white"><RefreshCw className="h-4 w-4" /></button></div></header>
    <div className="mx-auto max-w-7xl px-5 py-6"><div className="grid grid-cols-2 gap-2 sm:grid-cols-5">{tabs.map((item) => <button key={item.id} onClick={() => setTab(item.id)} className={`flex items-center justify-between rounded-md border p-3 text-left ${tab === item.id ? "border-navy bg-navy text-white" : "border-line bg-white"}`}><span className="flex items-center gap-2 text-sm font-semibold"><item.icon className="h-4 w-4" />{item.label}</span><span className="text-xs">{item.count}</span></button>)}</div>
      {loading ? <div className="py-20 text-center text-sm text-navy/50">正在读取工作队列...</div> : <div className="mt-5">
        {tab === "bindings" ? bindings.length ? <div className="divide-y divide-line rounded-md border border-line bg-white">{bindings.map((item) => { const resident = Array.isArray(item.resident) ? item.resident[0] : item.resident as Record<string, unknown> | null; const community = Array.isArray(item.community) ? item.community[0] : item.community as Record<string, unknown> | null; const network = Array.isArray(item.network) ? item.network[0] : item.network as Record<string, unknown> | null; return <article key={String(item.id)} className="flex flex-wrap items-center justify-between gap-4 p-4"><div><p className="font-semibold">{String(resident?.display_name ?? "待核验居民")}</p><p className="mt-1 text-xs text-navy/50">{String(community?.name ?? "未指定社区")} · {String(network?.name ?? "未指定家医网络")}</p><p className="mt-1 text-xs text-navy/40">登记时间：{new Date(String(item.created_at)).toLocaleString("zh-CN")}{resident?.phone ? ` · ${String(resident.phone)}` : ""}</p></div><div className="flex gap-2"><button onClick={() => void reviewBinding(String(item.id), "active")} className="inline-flex items-center gap-1 rounded-md bg-success px-3 py-2 text-xs font-semibold text-white"><CheckCircle2 className="h-4 w-4" />核验通过</button><button onClick={() => void reviewBinding(String(item.id), "pending")} className="inline-flex items-center gap-1 rounded-md border border-line px-3 py-2 text-xs font-semibold"><XCircle className="h-4 w-4" />退回补充</button></div></article>; })}</div> : <Empty text="没有待核验的居民签约登记。" /> : null}
        {tab === "facts" ? facts.length ? <div className="divide-y divide-line rounded-md border border-line bg-white">{facts.map((item) => { const resident = Array.isArray(item.resident) ? item.resident[0] : item.resident as Record<string, unknown> | null; return <article key={String(item.id)} className="p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-semibold">{String(item.fact_type)}</p><p className="mt-1 text-xs text-navy/45">{String(resident?.display_name ?? "未绑定群成员")} · 置信度 {Math.round(Number(item.confidence) * 100)}%</p></div><span className="rounded bg-risk-soft px-2 py-1 text-xs text-danger">待人工确认</span></div><pre className="mt-3 overflow-auto rounded-md bg-[#F4F6F5] p-3 text-xs leading-5">{JSON.stringify(item.structured_value, null, 2)}</pre><div className="mt-3 flex gap-2"><button onClick={() => void fact(String(item.id), "confirm")} disabled={!item.resident_id} className="inline-flex items-center gap-1 rounded-md bg-success px-3 py-2 text-xs font-semibold text-white disabled:opacity-40"><CheckCircle2 className="h-4 w-4" />确认入档</button><button onClick={() => void fact(String(item.id), "reject")} className="inline-flex items-center gap-1 rounded-md border border-line px-3 py-2 text-xs font-semibold"><XCircle className="h-4 w-4" />拒绝</button></div></article>; })}</div> : <Empty text="没有待确认的群事实。" /> : null}
        {tab === "content" ? content.length ? <div className="grid gap-3 lg:grid-cols-2">{content.map((item) => <article key={String(item.id)} className="rounded-md border border-line bg-white p-4"><p className="text-xs font-semibold text-sage">{String(item.source_name)} · {String(item.category)}</p><h2 className="mt-2 font-semibold">{String(item.title)}</h2><p className="mt-2 text-sm leading-6 text-navy/60">{String(item.summary)}</p><a href={String(item.original_url)} target="_blank" rel="noreferrer" className="mt-2 block text-xs font-semibold text-sage">查看原文</a><div className="mt-4 flex gap-2"><button onClick={() => void review(String(item.id), "publish")} className="rounded-md bg-success px-3 py-2 text-xs font-semibold text-white">审核发布</button><button onClick={() => void review(String(item.id), "reject")} className="rounded-md border border-line px-3 py-2 text-xs font-semibold">拒绝</button></div></article>)}</div> : <Empty text="没有待审核内容。" /> : null}
        {tab === "schedules" ? schedules.length ? <div className="divide-y divide-line rounded-md border border-line bg-white">{schedules.map((item) => { const practitioner = Array.isArray(item.practitioner) ? item.practitioner[0] : item.practitioner as Record<string, unknown> | null; const institution = Array.isArray(item.institution) ? item.institution[0] : item.institution as Record<string, unknown> | null; return <article key={String(item.id)} className="flex flex-wrap items-center justify-between gap-3 p-4"><div><p className="font-semibold">{String(practitioner?.name ?? "未指定医生")} · {String(institution?.name ?? "机构")}</p><p className="mt-1 text-xs text-navy/45">{new Date(String(item.starts_at)).toLocaleString("zh-CN")} · {String(item.status)}</p></div>{item.status === "draft" ? <div className="flex gap-2"><button onClick={() => void verify(String(item.id), "verified")} className="rounded-md bg-success px-3 py-2 text-xs font-semibold text-white">核验发布</button><button onClick={() => void verify(String(item.id), "cancelled")} className="rounded-md border border-line px-3 py-2 text-xs font-semibold">取消</button></div> : null}</article>; })}</div> : <Empty text="暂无排班。" /> : null}
        {tab === "broadcasts" ? broadcasts.length ? <div className="divide-y divide-line rounded-md border border-line bg-white">{broadcasts.map((item) => <article key={String(item.id)} className="p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{String(item.title)}</p><p className="mt-1 text-sm text-navy/55">{String(item.body)}</p></div><span className="rounded bg-health-soft px-2 py-1 text-xs text-sage">{String(item.status)}</span></div><p className="mt-2 text-xs text-navy/40">计划发送：{new Date(String(item.scheduled_at)).toLocaleString("zh-CN")}</p></article>)}</div> : <Empty text="暂无计划发送的群通知。" /> : null}
      </div>}
    </div></main>;
}

function Empty({ text }: { text: string }) { return <div className="rounded-md border border-dashed border-line bg-white p-10 text-center text-sm text-navy/50">{text}</div>; }
