export default defineAppConfig({
  __usePrivacyCheck__: true,
  lazyCodeLoading: "requiredComponents",
  sitemapLocation: "sitemap.json",
  permission: {
    "scope.record": {
      desc: "用于将您主动录制的语音转写为文字，录音仅在本次识别过程中临时使用。",
    },
  },
  networkTimeout: {
    request: 15000,
    uploadFile: 60000,
    downloadFile: 30000,
  },
  pages: [
    "pages/home/index",
    "pages/services/index",
    "pages/messages/index",
    "pages/me/index",
    "pages/ask/index",
    "pages/login/index",
    "pages/onboarding/index",
    "pages/family-link/index",
    "pages/privacy/index",
    "pages/notification-settings/index",
    "pages/account-security/index",
    "pages/legal/index",
    "pages/appointments/index",
    "pages/progress/index",
    "pages/health-records/index",
    "pages/public-info/index",
    "pages/browser/index",
    "pages/workbench/index",
  ],
  window: {
    backgroundTextStyle: "light",
    navigationBarBackgroundColor: "#EEF2F1",
    navigationBarTitleText: "家医 Claw",
    navigationBarTextStyle: "black",
    backgroundColor: "#EEF2F1",
  },
  tabBar: {
    color: "#66788A",
    selectedColor: "#102A43",
    backgroundColor: "#FFFFFF",
    borderStyle: "white",
    list: [
      { pagePath: "pages/home/index", text: "首页", iconPath: "assets/tabbar/home-default.png", selectedIconPath: "assets/tabbar/home-active.png" },
      { pagePath: "pages/services/index", text: "服务", iconPath: "assets/tabbar/services-default.png", selectedIconPath: "assets/tabbar/services-active.png" },
      { pagePath: "pages/messages/index", text: "消息", iconPath: "assets/tabbar/messages-default.png", selectedIconPath: "assets/tabbar/messages-active.png" },
      { pagePath: "pages/me/index", text: "我的", iconPath: "assets/tabbar/me-default.png", selectedIconPath: "assets/tabbar/me-active.png" },
    ],
  },
});
