"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Activity, ClipboardList, MessageCircleMore, Stethoscope, Users } from "lucide-react";

export default function DoctorPage() {
  const router = useRouter(); const [requests, setRequests] = useState<Array<Record<string, unknown>>>([]); const [facts, setFacts] = useState<Array<Record<string, unknown>>>([]); const [error, setError] = useState("");
  useEffect(() => { void Promise.all([fetch("/api/v1/staff/work-queue", { cache: "no-store" }), fetch("/api/v1/staff/group-work-queue", { cache: "no-store" })]).then(async ([work, group]) => { if (work.status === 401 || work.status === 403) return router.replace("/login"); const workPayload = await work.json(); const groupPayload = await group.json(); if (!work.ok) setError(workPayload.error?.message ?? "工作队列加载失败"); else setRequests(workPayload.data.requests ?? []); if (group.ok) setFacts(groupPayload.data.candidates ?? []); }).catch(() => setError("网络连接失败。")); }, [router]);
  const urgent = requests.filter((item) => ["high", "emergency"].includes(String(item.priority))).length;
  return <main className="min-h-dvh bg-[#F3F5F4] text-navy"><header className="border-b border-line bg-white"><div className="mx-auto max-w-7xl px-5 py-5"><p className="text-xs font-semibold text-sage">社区家庭医生团队</p><h1 className="mt-1 text-2xl font-semibold">工作台</h1><p className="mt-2 text-sm text-navy/50">处理服务申请，确认居民事实，不让 AI 越过人工审核</p></div></header><div className="mx-auto max-w-7xl px-5 py-6">{error ? <div className="rounded-md border border-danger/20 bg-risk-soft p-4 text-sm text-danger">{error}</div> : null}<section className="grid grid-cols-3 gap-3"><Metric label="待处理服务" value={requests.length} icon={ClipboardList} /><Metric label="高风险优先" value={urgent} icon={Stethoscope} /><Metric label="群事实待确认" value={facts.length} icon={MessageCircleMore} /></section><section className="mt-6 grid gap-3 md:grid-cols-2"><Link href="/workbench/requests" className="rounded-md border border-line bg-white p-5"><ClipboardList className="h-6 w-6 text-sage" /><h2 className="mt-4 font-semibold">服务工作队列</h2><p className="mt-2 text-sm leading-6 text-navy/55">受理、补充资料、提出时间、回写预约编号和完成服务。</p></Link><Link href="/workbench/operations" className="rounded-md border border-line bg-white p-5"><Activity className="h-6 w-6 text-sage" /><h2 className="mt-4 font-semibold">内容、排班与群运营</h2><p className="mt-2 text-sm leading-6 text-navy/55">审核公众号候选内容、核验排班、确认微信群居民事实。</p></Link></section><section className="mt-6 rounded-md border border-line bg-white p-5"><h2 className="flex items-center gap-2 font-semibold"><Users className="h-4 w-4 text-sage" />工作原则</h2><p className="mt-3 text-sm leading-6 text-navy/55">AI 只做分流和资料整理。诊疗判断、居民事实入档、排班发布与转诊处理均由有权限的工作人员确认。</p></section></div></main>;
}
function Metric({ label, value, icon: Icon }: { label: string; value: number; icon: typeof ClipboardList }) { return <div className="rounded-md border border-line bg-white p-4"><Icon className="h-4 w-4 text-sage" /><p className="mt-3 text-2xl font-semibold">{value}</p><p className="mt-1 text-xs text-navy/45">{label}</p></div>; }
